package types

exit_codes :: enum {
	OK,
	ERROR,
	OBJECT_IS_NIL,
	WORD_NOT_FOUND,
	UNEXPECTED_CHARACTER,
	PATH_CANT_BE_PARSED,
	EOF_IN_STRING,
	MEMORY_ALLOCATION_FAILED,
	FAILED_TO_READ_SOURCE_CODE_FILE,
	EOF_IN_SOURCE_CODE_REACHED,
	PEEK_OUT_OF_BOUNDS,
}
