package grammar

COMMENT: rune : '#'
NEWLINE: rune : '\n'
STRING_WRAPPER: rune : '"'
CHAR_WRAPPER: rune : '\''
BREAK: string : "break"
CONST: string : "const"
CONTINUE: string : "continue"
ELSE: string : "else"
ELSE_IF: string : "elif"
ERROR: string : "err"
EXISTS: string : "exists"
FOR: string : "for"
FALSE: string : "false"
FUNCTION: string : "fn"
IF: string : "if"
NULL: string : "null"
MODULE: string : "module"
OR: string : "!!"
OUT: string : "out"
LENGTH: string : "len"
PRINT_LINE: string : "println"
PRINT: string : "print"
RETURN: string : "return"
FILE_REMOVE: string : "rm"
REMOVE: string : "remove"
TRUE: string : "true"
VAR: string : "var"
WHILE: string : "while"
TIME: string : "time"
IN: string : "in"
SLEEP: string : "sleep"
KEY: string : "key"
